INSERT INTO AUTHORITY               VALUES(1,'ROLE_OAUTH_ADMIN');
INSERT INTO AUTHORITY               VALUES(2,'ROLE_RESOURCE_ADMIN');
INSERT INTO AUTHORITY               VALUES(3,'ROLE_PRODUCT_ADMIN');
INSERT INTO CREDENTIALS             VALUES(1, '1','oauth_admin','$2a$10$BurTWIy5NTF9GJJH4magz.9Bd4bBurWYG8tmXxeQh1vs7r/wnCFG2','0');
INSERT INTO CREDENTIALS             VALUES(2, '1','resource_admin','$2a$10$BurTWIy5NTF9GJJH4magz.9Bd4bBurWYG8tmXxeQh1vs7r/wnCFG2','0');
INSERT INTO CREDENTIALS             VALUES(3, '1','product_admin','$2a$10$BurTWIy5NTF9GJJH4magz.9Bd4bBurWYG8tmXxeQh1vs7r/wnCFG2','0');
INSERT INTO CREDENTIALS_AUTHORITIES VALUES (1,1);
INSERT INTO CREDENTIALS_AUTHORITIES VALUES (2,2);
INSERT INTO CREDENTIALS_AUTHORITIES VALUES (3,3);