spring:
  datasource:
      type : com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:h2:file:~/aas/aas
      password: sa
      username: sa
      hikari :
        minimumIdle : 5
        maximumPoolSize : 20
        idleTimeout : 30000
        poolName : SpringBootJPAHikariCP
        maxLifetime : 2000000
        connectionTimeout : 30000
  jpa :
    hibernate :
      ddl-auto: none
    properties :
      hibernate :
        show_sql : true
        dialect  : org.hibernate.dialect.H2Dialect
# --- server
server:
  port: 8081



